# Generated by Django 2.2 on 2019-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('rut_alumno', models.CharField(max_length=10)),
            ],
        ),
    ]
