# Generated by Django 2.2 on 2019-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='evento_asisitio_alumno',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
