# Generated by Django 2.2 on 2019-04-29 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0003_auto_20190422_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado_evento',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
