# Generated by Django 2.2 on 2019-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0004_auto_20190428_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado_evento',
            field=models.CharField(choices=[('Ativo', 'Activo'), ('Cerrado', 'Cerrado')], max_length=20, null=True),
        ),
    ]
