# Generated by Django 2.2 on 2019-04-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0006_auto_20190429_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado_evento',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Activo', max_length=20, null=True),
        ),
    ]
