# Generated by Django 2.2 on 2019-04-29 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0007_auto_20190429_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_evento_asistio_alumno',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
