# Generated by Django 2.2 on 2019-04-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citt', '0008_alumno_fecha_evento_asistio_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno_duoc',
            fields=[
                ('id_alumno_duoc', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('rut_alumno_duoc', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_alumno_duoc', models.CharField(blank=True, max_length=80, null=True)),
                ('carrera_alumno_duoc', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera_alumno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_alumno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
